# python:alpine is 3.{latest}
FROM python:2-stretch 

RUN wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb && \
    dpkg -i pandoc-2.7.3-1-amd64.deb

ENV APP /src

WORKDIR /src

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /src/

EXPOSE 5000

CMD [ "uwsgi", "--ini", "/src/app.ini" ]