# docker-compose.yml
version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/src"
      # - asset-volume:/src
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
    volumes:
      - "./:/src"
      # - asset-volume:/src
volumes:
  asset-volume: